services:
  db:
    image: postgres:15-alpine
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: localpassword123
      POSTGRES_DB: media_app
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data

volumes:
  local_pgdata: